<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application Backend' => 'Панель администратора',
    'Books' => 'Книги',
    'ID' => 'ID',
    'My Yii Application Backend' => 'Панель администратора приложения Yii',
    'Save' => 'Сохранить',
    'The requested page does not exist.' => 'Запрошенная страница не найдена.',
    'Title' => 'Название',
    'Update Book: {name}' => 'Редактирование книги: {name}',
    'Chapters' => 'Главы',
    'Page From' => 'Начальная страница',
    'Page To' => 'Конечная страница',
    'Update' => 'Редактировать',
    'Update Chapter' => 'Редактирование главы',
    'Update Chapter: {name}' => 'Редактирование главы: {name}',
    'Please fill out the following fields to login (use <code>admin/admin</code> for the purposes of demonstration):' => 'Для входа в систему заполните следующие поля (для демонстрационного входа используйте параметры учетной записи <code>admin/admin</code>):',
    'Login' => 'Вход',
    'Home' => 'Главная',
    'Logout ({user})' => 'Выход ({user})',
];
